
from sqlalchemy import Column, Integer, String, Date, Float
from infra.configs.base import Base


class Salvado(Base):
    __tablename__ = "salvados"

    id = Column(Integer, primary_key=True, autoincrement=True)
    status = Column(String)
    sinistro = Column(String)
    apolice = Column(String)
    data_recebimento_salvado = Column(Date)
    data_pedido_cotacao_remocao = Column(Date)
    nome_segurado = Column(String)
    nome_terceiro = Column(String)
    placa = Column(String(7), nullable=True, unique=True)
    marca = Column(String)
    modelo = Column(String)
    ano = Column(String)
    n_fipe = Column(String)
    valor_fipe = Column(Float)
    mes_ano_ref_fipe = Column(String)
    leiloeiro = Column(String)
    status_remocao_leiloeiro = Column(String)
    local_atual_veiculo = Column(String)
    data_entrada_patio_leiloeiro = Column(Date)
    vistorias_solicitada_monta = Column(Date)
    vistorias_recebidas_monta = Column(Date)
    vistorias_solicitada_ecv = Column(Date)
    vistorias_recebidas_ecv = Column(Date)
    classificacao_danos = Column(String)
    ecv = Column(String)
    valor_total_indenizacao = Column(Float)
    franquia_outros_descontos = Column(Float)
    valor_pago_pela_cia = Column(Float)
    data_pagto_indenizacao = Column(Date)
    data_recebimento_docs_nf_entrada = Column(Date)
    data_solicitacao_nf_entrada = Column(Date)
    data_recebimento_nf_entrada = Column(Date)
    n_nf_entrada = Column(String)
    valor_nf_entrada = Column(Float)
    data_solicitacao_nf_saida = Column(Date)
    data_recebimento_nf_saida = Column(Date)
    n_nf_saida = Column(String)
    valor_nf_saida = Column(Float)
    data_solicitacao_recorte_chassi = Column(Date)
    data_recebimento_recorte_chassi = Column(Date)
    data_docs_disponivel_transf_seguradora = Column(Date)
    data_recebimento_docs_transf_seguradora = Column(Date)
    data_venda_salvado = Column(Date)
    valor_venda = Column(Float)
    nome_arrematante = Column(String)
    data_docs_disponivel_transf_arrematante = Column(Date)
    data_recebimento_docs_transf_arrematante = Column(Date)
    doc_transferido_arrematante = Column(String)
    analista_responsavel = Column(String)
    historico = Column(String)
